[tool.poetry]
name = "diary-backend"
version = "0.1.0"
description = ""
authors = ["Optimize Success <optimizesuccess4@gmail.com>"]
readme = "README.md"
packages = [{include = "diary_backend"}]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.101.1"
uvicorn = {extras = ["standard"], version = "^0.23.2"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
